=== consultant-1379/Eniq_Platforms/mediation/dev/export/jar/xsd/group_management.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
  /**
   * <p/>
   * (C) Copyright Ericsson Radio Systems AB, 2005
   * <p/>
   * The copyright to the computer program(s) herein is the property of Ericsson
   * Radio Systems AB, Sweden. The program(s) may be used and/or copied only with
   * the written permission from Ericsson Radio System AB or in accordance with
   * the terms and conditions stipulated in the agreement/contract under which
   * the program(s) have been supplied.
   * <p/>
   */
  -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="group">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="group-element" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="group-element">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="key" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="groupmgt">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="group" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="key">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
			<xs:attribute name="start-time" type="xs:date" use="optional"/>
			<xs:attribute name="stop-time" type="xs:date" use="optional" default="9999-12-31"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== consultant-1379/Eniq_Platforms/mediation/dev/export/test/xml/imsi_fpgroups.xml
<?xml version="1.0" encoding="UTF-8"?>
<groupmgt xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/group_management.xsd">
	<group type="imsi" name="imsi-4">
		<group-element>
			<key name="imsi" value="93"/>
		</group-element>
	</group>
	<group type="imsi" name="imsi-5">
		<group-element>
			<key name="imsi" value="902"/>
		</group-element>
	</group>
	<group type="imsi" name="TopDataConsumers_010101">
		<group-element>
			<key name="imsi" value="111111"/>
		</group-element>
	</group>
	<group type="imsi" name="TopDataConsumers_010104">
		<group-element>
			<key name="imsi" value="444"/>
		</group-element>
	</group>
</groupmgt>
